TITLE Trabajo 1
;DESCRPICION 
;Objetivo: Primera ejecucion de masm
;
; Autore(s):
;         Garcia Ruiz Alejandro H.
; Semestre: 8vo Semestre ISC 
;FIN DESCRPICION
INCLUDE Irvine32.inc  
.data
; Area de Declaracion de Variables
msjEntrada_10 db "Ingresa una Calificacion: ", 0
msjResultado_10 db "El promedio es: ", 0

.code
	main10 PROC
		;Logica del Programa

		MOV EDX, OFFSET MSJENTRADA_10   ;CALIFICACION1
		CALL WRITESTRING
		CALL CRLF

		CALL READINT  ; LEE UN NUMERO Y LO GUARDA EN EAX
		; DISPONIBLES EBX, ECX ... PARA RESGUARDAR EL VALOR
		MOV EBX, EAX ; GUARDA EL VALOR DE EAX EN EBX

		MOV EDX, OFFSET MSJENTRADA_10  ; CALIFICACION2
		CALL WRITESTRING
		CALL CRLF

		CALL READINT ; LEE UN NUMERO Y LO GUARDA EN EAX
		; RESGUARDAR U OPERAR  ....
		; --- OPERAR: (SUMAR)
		ADD EBX, EAX   ; CAL 1 + CAL 2

		MOV EDX, OFFSET MSJENTRADA_10 ; CALIFICACION 3
		CALL WRITESTRING
		CALL CRLF

		CALL READINT ; LEE UN NUMERO Y LO GUARDA EN EAX
		; RESGUARDAR U OPERAR  ....
		; --- OPERAR: (SUMAR)
		ADD EBX, EAX   ; (CAL 1 + CAL 2) + CAL3


		MOV EDX, OFFSET MSJENTRADA_10  ;CALIFICACION 4
		CALL WRITESTRING
		CALL CRLF

		CALL READINT ; LEE UN NUMERO Y LO GUARDA EN EAX
		; RESGUARDAR U OPERAR  ....
		; --- OPERAR: (SUMAR)
		ADD EBX, EAX   ; (CAL 1 + CAL 2 + CAL 3) + CAL 4

		MOV EDX, OFFSET MSJENTRADA_10  ; CALIFICACION 5
		CALL WRITESTRING
		CALL CRLF

		CALL READINT ; LEE UN NUMERO Y LO GUARDA EN EAX
		; RESGUARDAR U OPERAR  ....
		; --- OPERAR: (SUMAR)  .. PERO GUARDAR EN EAX, PARA
		; FACILITAR LA PROXIMA DIVISION  
		ADD EAX, EBX   ; CAL 5 +(CAL 1 + CAL 2 + CAL 3 + CAL 4)


		MOV EDX, OFFSET MSJRESULTADO_10  ;RESULTADO
		CALL WRITESTRING
		CALL CRLF

		;LA DIVISION SIEMPRE ES EAX / ...
		;DIVISION EAX ENTRE UN REGISTRO O UNA VARIABLE
		;
		; REQUIERE QUE EDX SE ENCUENTRE EN 0, PARA EVITAR OVERFLOW

		MOV EDX, 0 ; PARA GUARDAR EL RESIDUO

		;_HASTA ESTE PUNTO ECX, NO CUENTA CON ALGUN VALOR DE UTILIDAD
		; Y EN EBX, EL VALOR YA NO SE UTILIZARA, PORQUE YA FUE UTILIZADO AL REALIZAR LA SUMA ANTERIOR
		; EN ESTE SENTIDO, SE PUEDE UTILIZAR EBX O ECX.. SE ESCOGIO ECX..
		MOV ECX, 5
		DIV ECX  ; EL COCIENTE SE GUARDA EN EAX

		CALL WRITEINT
		
		exit	
	main10 ENDP
	END main10